openapi: 3.0.0
servers:
  - url: "https://samples.openweathermap.org"
info:
  description: This is a mock backend for weather service
  version: 1.0.0
  title: Weather Service
tags:
  - name: weather
    description: Open Weather API
x-wso2-basePath: /weatherservice/v1
x-wso2-production-endpoints:
  urls:
    - "https://samples.openweathermap.org/data/2.5"
x-wso2-response-interceptor: transformXmlToJson
paths:
  /weather:
    get:
      tags:
        - weather
      parameters:
        - name: q
          in: query
          description: Query
          required: false
          schema:
            type: string
        - name: appid
          in: query
          description: AppId
          required: false
          schema:
            type: string
        - name: mode
          in: query
          description: format
          required: false
          schema:
            type: string
      summary: Get current weather in a given city
      description: Get current weather in a given city
      operationId: getWeather
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Weather"
        "400":
          description: Invalid status value
components:
  schemas:
    Weather:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: Jack
        lastName:
          type: string
          example: Steel
        location:
          type: string
          example: US
  requestBodies:
    Weather:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Weather"
      description: Employee object that needs to be added
      required: true

