openapi: 3.0.0
servers:
  - url: "https://www.mocky.io/v2/5d24de7f2f000008be241c45"
  - url: "http://www.mocky.io/v2/5d24de7f2f000008be241c45"
info:
  description: This is a mock backend for employee service
  version: 1.0.0
  title: Employee Service
tags:
  - name: employee
    description: Employee record management system
x-wso2-basePath: /empservice/v1
x-wso2-production-endpoints:
  urls:
    - "http://www.mocky.io/v2/5d24de7f2f000008be241c45"
paths:
  /employee:
    post:
      tags:
        - employee
      summary: Add employee record
      description: Add employee record
      operationId: addEmployee
      x-wso2-request-interceptor: transformJsonToXml
      responses:
        "201":
          description: successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Employee"
        "400":
          description: Invalid status value
      x-auth-type: "Application & Application User"
      x-throttling-tier: Unlimited
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: "#/components/schemas/Employee"
components:
  schemas:
    Employee:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
          example: Jack
        lastName:
          type: string
          example: Steel
        location:
          type: string
          example: US
  requestBodies:
    Employee:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Employee"
      description: Employee object that needs to be added
      required: true

